apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openhab.fullname" . }}-config
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.configYaml | nindent 4 }}
