apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openhab.fullname" . }}
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openhab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openhab.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "openhab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      volumes:
      - name: openhab
        persistentVolumeClaim:
          claimName: openhab
      - name: zstick-zwave
        hostPath:
          path: /dev/ttyUSB0
      - name: zstick-zigbee
        hostPath:
          path: /dev/ttyUSB1
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/Los_Angeles
          type: File

      initContainers:
      - name: init-openhab
        image: busybox:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          while [ ! $(ls /final_configs | wc -l) -gt 0 ]; do
            echo 'no configs found; waiting 5s'
            sleep 5
          done
          echo 'configs found; starting'
        volumeMounts:
        - name: openhab
          mountPath: /final_configs
          subPath: conf
          readOnly: true

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
          {{- include "openhab.extraEnvironmentVars" .Values.server | nindent 10 }}
        volumeMounts:
        - name: zstick-zwave
          mountPath: /dev/ttyUSB0
        - name: zstick-zigbee
          mountPath: /dev/ttyUSB1
        - name: openhab
          mountPath: /openhab/conf
          subPath: conf
        - name: openhab
          mountPath: /openhab/addons
          subPath: addons
        - name: openhab
          mountPath: /openhab/userdata
          subPath: userdata
        - name: tz-config
          mountPath: /etc/localtime
          readOnly: true

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}








spec:
  template:
    spec:
      containers:
        - ports:
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
