{{- if .Values.rsync_backup.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "unifi.fullname" . }}-config-backup
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.rsync_backup.schedule }}"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      template:
        spec:
          containers:
          - name: hello
            image: pebalk/rsync
            imagePullPolicy: IfNotPresent
            command: ["/usr/bin/rsync"]
            args:
            - "--archive"
            - "--compress"
            - "--delete"
            - "--verbose"
            - "--rsh \"ssh -i /root/ssh/id_rsa\""
            - "{{ .Values.rsync_backup.config_dir_path  }}"
            - "{{ .Values.rsync_backup.user }}@{{ .Values.rsync_backup.ip }}::{{ .Values.rsync_backup.backup_dir_path}}"
            volumeMounts:
            - mountPath: /unifi/data
              name: unifi-data
              subPath: {{ ternary "data" (printf "%s/%s" .Values.persistence.subPath "data") (empty .Values.persistence.subPath) }}
            - mountPath: /root/ssh
              name: backup-ssh-key
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: unifi-data
            persistentVolumeClaim:
              claimName: {{ include "unifi.fullname" . }}
          - name: backup-ssh-key
            secret:
              secretName: {{ include "unifi.fullname" . }}-ssh-key
{{- end -}}
