{{- if .Values.ingressroute.enabled -}}
{{- $fullName := include "unifi.fullname" . -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-controller
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
  {{- with .Values.ingressroute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - webalt
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - kind: Service
      name: {{ $fullName }}
      port: 8080
{{- end }}
