---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: controller
    port: 8080
    targetPort: controller
    protocol: TCP
  - name: discovery
    port: 10001
    targetPort: discovery
    protocol: UDP
  - name: https-gui
    port: 8443
    targetPort: https-gui
    protocol: TCP
  - name: speedtest
    port: 6789
    targetPort: speedtest
    protocol: TCP
  - name: stun
    port: 3478
    targetPort: stun
    protocol: UDP
  - name: syslog
    port: 5514
    targetPort: syslog
    protocol: UDP
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
